### ISSUE TITLE
LD_SLSQP does not terminate on NaN

### ISSUE THREAD

**Issue by joehuchette** [jump-dev/NLopt.jl#31] opened 2015-01-28 20:39 UTC
``` jl
using JuMP
using NLopt
m = Model(solver=NLoptSolver(algorithm=:LD_SLSQP))
@defVar(m, c[1:2] >= 0)
@addConstraint(m, sum(c) <= 2)
@setNLObjective(m, Max, (c[1] + 0.7*c[2])^0.5 - (0.7*c[2])^0.5 + (c[2] + 0.7*c[1])^0.5 - (0.7*c[1])^0.5)
solve(m)
```

This hangs for a while, and when I manually exit, I get 

```
ERROR: InterruptException:
 in eval_g at /Users/huchette/.julia/v0.4/JuMP/src/nlp.jl:274
 in g_ineq at /Users/huchette/.julia/v0.4/NLopt/src/NLoptSolverInterface.jl:179
 in nlopt_vcallback_wrapper at /Users/huchette/.julia/v0.4/NLopt/src/NLopt.jl:469
 in optimize! at /Users/huchette/.julia/v0.4/NLopt/src/NLopt.jl:509
 in optimize! at /Users/huchette/.julia/v0.4/NLopt/src/NLoptSolverInterface.jl:203
 in solvenlp at /Users/huchette/.julia/v0.4/JuMP/src/nlp.jl:491
 in solve at /Users/huchette/.julia/v0.4/JuMP/src/solvers.jl:9
```

cc @mlubin

**Comment by stevengj** [comment] 2015-01-28 21:05
Does the `~/.julia/NLopt/test/tutorial_jump.jl` example work?

**Comment by joehuchette** [comment] 2015-01-28 21:22
Yep, that one works great. MWE:
```jl
using JuMP, NLopt
m = Model(solver=NLoptSolver(algorithm=:LD_MMA)) # or :LD_SLSQP
@defVar(m, c >= 0)
@setNLObjective(m, Min, sqrt(c))
solve(m)
```

**Comment by stevengj** [comment] 2015-01-28 21:24
What does "MWE" mean?

**Comment by joehuchette** [comment] 2015-01-28 21:25
Minimal working example, sorry.

**Comment by mlubin** [comment] 2015-01-28 22:34
The hang is apparently inside JuMP code, but doesn't occur when another solver like Ipopt is used. Pretty strange.

**Comment by mlubin** [comment] 2015-01-31 03:29
It's not hanging, it's just iterating without converging.

**Comment by stevengj** [comment] 2015-02-02 16:02
Which part is iterating?

**Comment by mlubin** [comment] 2015-02-02 16:03
NLopt

**Comment by stevengj** [comment] 2015-02-02 16:48
What are the termination criteria?  I don't see any tolerances.

**Comment by odow** [comment] 2022-03-03 03:00
Just confirming that this is still a problem
```Julia
using JuMP
import NLopt
m = Model(NLopt.Optimizer)
set_optimizer_attribute(m, "algorithm", :LD_SLSQP)
@variable(m, c[1:2] >= 0)
@constraint(m, sum(c) <= 2)
@NLobjective(m, Max, (c[1] + 0.7*c[2])^0.5 - (0.7*c[2])^0.5 + (c[2] + 0.7*c[1])^0.5 - (0.7*c[1])^0.5)
optimize!(m)
```
Although you could set time limits or tolerances to exit earlier:
```Julia
julia> using JuMP

julia> import NLopt

julia> m = Model(NLopt.Optimizer)
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: NLopt

julia> set_optimizer_attribute(m, "algorithm", :LD_SLSQP)

julia> set_optimizer_attribute(m, "maxtime", 3.0)

julia> @variable(m, c[1:2] >= 0, start = 0)
2-element Vector{VariableRef}:
 c[1]
 c[2]

julia> @constraint(m, sum(c) <= 2)
c[1] + c[2] ≤ 2.0

julia> @NLobjective(m, Max, (c[1] + 0.7*c[2])^0.5 - (0.7*c[2])^0.5 + (c[2] + 0.7*c[1])^0.5 - (0.7*c[1])^0.5)

julia> @time optimize!(m)
  3.005593 seconds (14.77 M allocations: 676.120 MiB, 4.12% gc time, 0.18% compilation time)

julia> termination_status(m)
TIME_LIMIT::TerminationStatusCode = 12
```

**Comment by odow** [comment] 2023-01-25 02:45
So the issue is that the derivatives aren't defined at the default starting point of `0.0`. 

It seems like for this algorithm NLopt just lets NaN accumulate and doesn't error. Should it? Or are there some algorithms that support NaN and can recover?

**Comment by odow** [comment] 2024-08-21 21:55
@stevengj I'd appreciate your feedback on this issue. What is the expected behavior when functions or gradients return `NaN`?

I bumped into this during https://github.com/JuliaOpt/NLopt.jl/pull/239/files#diff-1c91bbf6e133c9ebca6c69381a02bb628595d0216a3a095e281ddba57d495b9cR236-R237

**Comment by odow** [comment] 2024-08-22 00:50
It seems like this is a known issue with some algorithms. https://github.com/stevengj/nlopt/pull/38

But it is intended behavior for others: https://github.com/stevengj/nlopt/issues/279#issuecomment-521981655

So perhaps we just close this issue and deal with the consequences. No one else has come along to comment in nearly 10 years.

**Comment by odow** [comment] 2024-08-22 22:02
The conclusion of the monthly developer call is that we should close this issue because it is nearly 10 years old, and because it is a "feature" of the upstream library. We shouldn't intercept `NaN` calls in NLopt.jl. (I'll also file this away as related to https://github.com/jump-dev/JuMP.jl/issues/3664. It'd be good to be able to evaluate starting points of nonlinear programs to detect feasibility, gradients, etc.)

**Closed by odow** 2024-08-22 22:02 UTC
Labels: upstream
